### ISSUE TITLE
Translate a MCM KPP file to MICM format

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm-kpp#14]
Create a MICM/MusicBox configuration from the attached KPP file
[mcm_export.eqn.txt](https://github.com/user-attachments/files/15875838/mcm_export.eqn.txt)

Requested by: changminc@ucar.edu

**Comment by dwfncar** [comment]
All reactions are defined by formulas, so will need to think about an expression parser that recognizes Troe, Arrhenius forms, etc ...

**Comment by mattldawson** [comment]
This was brought up in the 7/2/24 meeting with the ACOM scientists (https://docs.google.com/document/d/1MqetfdJn9mpt5OOweuRzgiw4mciDGKYgiCchyNj2x1c/edit). Louisa is going to get in touch with the MCM developers to see if they would be willing to output directly to MICM format

**Comment by dwfncar** [comment]
Closing issue.
